### ISSUE TITLE
'utf-8' codec can't decode byte 0xdf in position 9

### ISSUE THREAD

**Issue by dhirajeadara4gramener** [gramener/gramex-guide#11]
When I run gramex init I get the following issue:
```
Traceback (most recent call last):
  File "/home/edhiraj/.miniconda/envs/delivery/bin/gramex", line 10, in <module>
    sys.exit(commandline())
  File "/home/edhiraj/.miniconda/envs/delivery/lib/python3.7/site-packages/gramex/__init__.py", line 177, in commandline
    callback(**kwargs)
  File "/home/edhiraj/.miniconda/envs/delivery/lib/python3.7/site-packages/gramex/install.py", line 650, in init
    _copy(source, target, template_data=data)
  File "/home/edhiraj/.miniconda/envs/delivery/lib/python3.7/site-packages/gramex/install.py", line 617, in _copy
    result = Template(result).generate(**template_data)
  File "/home/edhiraj/.miniconda/envs/delivery/lib/python3.7/site-packages/tornado/template.py", line 302, in __init__
    reader = _TemplateReader(name, escape.native_str(template_string),
  File "/home/edhiraj/.miniconda/envs/delivery/lib/python3.7/site-packages/tornado/escape.py", line 217, in to_unicode
    return value.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdf in position 9: invalid continuation byte

```
However, the project does get initialised

**Comment by bkamapantula** [comment]
this should be resolved via https://github.com/gramener/gramex/commit/cf1264378b9c2199993dba06d34de1bafffcf2e6

available in [v1.61](https://learn.gramener.com/guide//release/1.61/#improved-gramex-init)
